components:
  battery_1:
    type: battery
    model:
      type: simple
      efficiency: 0.9
      max_power: 10.0
      capacity: 20.0
      init_soc: 0.5
      deadband: 0.1

thermal_model:
  thermal_model_type: simple_air
  params:
    building_volume: 300.0

dataset:
  data_source:
    type: "file"
    file_path: "data/building_timeseries.csv"
    time_column: "timestamp"
  params:
    feature_columns:
      price: "electricity_price"
      pv: "pv_generation"
      load: "base_load"
      ambient_temperature: "ambient_temp"
    dt_seconds: 900
    use_time_features: False # enable this to get time features
    prediction_horizon: 4 # 4 steps of 15 min = 1 hour ahead