components:
  battery_1:
    type: battery
    model:
      type: simple
      efficiency: 0.9
      max_power: 10.0
      capacity: 20.0
      init_soc: 0.5
      deadband: 0.1
    sensor:
      observe_electrical_soc: true
      observe_thermal_soc: false
      observe_electrical_flow: true
      observe_heating_flow: false
      observe_cooling_flow: false
      soc_noise_std: 0.01
      flow_noise_std: 0.1

thermal_sensor:
  observe_indoor_temp: true
  observe_temp_error: false
  observe_comfort_violation: false
  observe_zone_temps: false
  temp_noise_std: 0.0

thermal_model:
  thermal_model_type: simple_air
  params:
    building_volume: 300.0

dataset:
  data_source:
    type: file
    file_path: dataset.csv
    time_column: time
  params:
    feature_columns: 
      price: price_$
      pv: pv_kW
      load: load_kW
    dt_seconds: 900
    use_time_features: true

reward_manager:
  rewards:
    energy_cost:
      weight: -1.0
    comfort_violation:
      weight: -10.0
    battery_degradation:
      weight: -0.1
      
params:
  random_seed: 42

wrappers:
  action_space:
    discrete_bins:
      battery_1: 5
      battery_2: 3
      battery_4: 7
    clip_actions: true

  observation_space:
    noise_std: 0.01
    framestack_size: 4
    normalize: true
    time_aware: true

  misc:
    max_episode_steps: 100